### ISSUE TITLE
Dataset on huggingface

### ISSUE THREAD

**Issue by SophieZheng998** [Unispac/shallow-vs-deep-alignment#1]
Your work is really interesting, here I want to download the dataset from the link:https://huggingface.co/datasets/Unispac/shallow-vs-deep-safety-alignment-dataset/, but the webpage appears broken?

**Comment by Unispac** [comment]
Thank you for flagging this.
Hmm, It seems to be the problem of huggingface and is likely to be a temporary failure on their end. 

Let's check in later and see whether it will be fixed by huggingface.
